// LOCALHOST
### Get all users
GET http://localhost:3000/users


### Get contact by id
Get http://localhost:3000/users/6870763a8c58e500bba1a2e7


### Create contact
POST http://localhost:3000/users HTTP/1.1
Content-type: application/json

{
    "email": "test@example.com",
    "username": "test@test.com",
    "name": "Hello!",
    "ipaddress": "75.169.235.66"
}

### PUT contact
PUT http://localhost:3000/users/6870763a8c58e500bba1a2e7 HTTP/1.1
Content-Type: application/json

{
    "email": "test@example.com",
    "username": "test@test.com",
    "name": "Hello!",
    "ipaddress": "75.169.235.66"
}


### DELETE contact
DELETE http://localhost:3000/users/6877352770a05756313efca9